version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/myapp --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  api:
    build: ./server
    container_name: goapp
    environment:
      HTTP_LISTEN_ADDRESS: 5000
      JWT_SECRET: secretsecretsecretsecretsecretsecretsecretsecret
      MONGO_DB_NAME: hotel-reservation
      MONGO_DB_URI: mongodb://root:password@mongodb/?authSource=admin
      MONGO_DB_NAME_TEST: hotel-reservation-test
      MONGO_DB_URI_TEST: mongodb://root:password@mongodb/?authSource=admin
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  data:
  logs:
