version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: mongo
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/myapp --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  api:
    build: ./server/hr
    container_name: hc_api
    environment:
      HTTP_LISTEN_ADDRESS: 5000
      JWT_SECRET: secretsecretsecretsecretsecretsecretsecretsecret
      MONGO_DB_NAME: hotel-reservation
      MONGO_DB_URI: mongodb://root:password@mongodb/?authSource=admin
      MONGO_DB_NAME_TEST: hotel-reservation-test
      MONGO_DB_URI_TEST: mongodb://root:password@mongodb/?authSource=admin
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 22181:2181
  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     # - 29092:29092
  #     - 9092:9092
  #   hostname: kafka
  #   environment:
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  # obu:
  #   build: ./server/tc/obu
  #   container_name: obu_api
  #   depends_on:
  #     - data_receiver
  # data_receiver:
  #   build: ./server/tc/data_receiver
  #   container_name: data_receiver_api
  #   ports:
  #     - "30000:30000"
  #   depends_on:
  #     - kafka
  # distance_calculator:
  #   build: ./server/tc/distance_calculator
  #   container_name: distance_calculator_api
  #   depends_on:
  #     - data_receiver
  # data_aggregator:
  #   build: ./server/tc/data_aggregator
  #   container_name: data_aggregator_api
  #   depends_on:
  #     - kafka

volumes:
  data:
  logs:
