version: "3.6"

services:
  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concurrency
    volumes:
      - db-data/:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped
    # volumes:
    #   - ./db-data/redis/:/data/
    volumes:
      - cache:/data

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  db-data:
  cache:
