version: "3.6"

services:
  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: withpsql
    volumes:
      - pgdb-data1:/var/lib/postgresql/data1/

  withpsqlrestapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    environment:
      - HTTP_PORT=9000
      - DSN=host=postgres port=5432 user=postgres password=password dbname=postgres sslmode=disable timezone=UTC connect_timeout=5

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   # volumes:
  #   #   - ./db-data/redis/:/data/
  #   volumes:
  #     - cache:/data

volumes:
  pgdb-data1:
  cache:
