// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package mocks

//go:generate minimock -i gateway/internal/service.NoteService -o note_service_minimock.go -n gatewayerviceMock -p mocks

import (
	"context"
	"gateway/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// gatewayerviceMock implements service.NoteService
type gatewayerviceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, info *model.NoteInfo) (i1 int64, err error)
	inspectFuncCreate   func(ctx context.Context, info *model.NoteInfo)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mgatewayerviceMockCreate

	funcGet          func(ctx context.Context, id int64) (np1 *model.Note, err error)
	inspectFuncGet   func(ctx context.Context, id int64)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mgatewayerviceMockGet
}

// NewgatewayerviceMock returns a mock for service.NoteService
func NewgatewayerviceMock(t minimock.Tester) *gatewayerviceMock {
	m := &gatewayerviceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mgatewayerviceMockCreate{mock: m}
	m.CreateMock.callArgs = []*gatewayerviceMockCreateParams{}

	m.GetMock = mgatewayerviceMockGet{mock: m}
	m.GetMock.callArgs = []*gatewayerviceMockGetParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mgatewayerviceMockCreate struct {
	mock               *gatewayerviceMock
	defaultExpectation *gatewayerviceMockCreateExpectation
	expectations       []*gatewayerviceMockCreateExpectation

	callArgs []*gatewayerviceMockCreateParams
	mutex    sync.RWMutex
}

// gatewayerviceMockCreateExpectation specifies expectation struct of the gatewayervice.Create
type gatewayerviceMockCreateExpectation struct {
	mock    *gatewayerviceMock
	params  *gatewayerviceMockCreateParams
	results *gatewayerviceMockCreateResults
	Counter uint64
}

// gatewayerviceMockCreateParams contains parameters of the gatewayervice.Create
type gatewayerviceMockCreateParams struct {
	ctx  context.Context
	info *model.NoteInfo
}

// gatewayerviceMockCreateResults contains results of the gatewayervice.Create
type gatewayerviceMockCreateResults struct {
	i1  int64
	err error
}

// Expect sets up expected params for gatewayervice.Create
func (mmCreate *mgatewayerviceMockCreate) Expect(ctx context.Context, info *model.NoteInfo) *mgatewayerviceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("gatewayerviceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &gatewayerviceMockCreateExpectation{}
	}

	mmCreate.defaultExpectation.params = &gatewayerviceMockCreateParams{ctx, info}
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the gatewayervice.Create
func (mmCreate *mgatewayerviceMockCreate) Inspect(f func(ctx context.Context, info *model.NoteInfo)) *mgatewayerviceMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for gatewayerviceMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by gatewayervice.Create
func (mmCreate *mgatewayerviceMockCreate) Return(i1 int64, err error) *gatewayerviceMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("gatewayerviceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &gatewayerviceMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &gatewayerviceMockCreateResults{i1, err}
	return mmCreate.mock
}

// Set uses given function f to mock the gatewayervice.Create method
func (mmCreate *mgatewayerviceMockCreate) Set(f func(ctx context.Context, info *model.NoteInfo) (i1 int64, err error)) *gatewayerviceMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the gatewayervice.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the gatewayervice.Create method")
	}

	mmCreate.mock.funcCreate = f
	return mmCreate.mock
}

// When sets expectation for the gatewayervice.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mgatewayerviceMockCreate) When(ctx context.Context, info *model.NoteInfo) *gatewayerviceMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("gatewayerviceMock.Create mock is already set by Set")
	}

	expectation := &gatewayerviceMockCreateExpectation{
		mock:   mmCreate.mock,
		params: &gatewayerviceMockCreateParams{ctx, info},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up gatewayervice.Create return parameters for the expectation previously defined by the When method
func (e *gatewayerviceMockCreateExpectation) Then(i1 int64, err error) *gatewayerviceMock {
	e.results = &gatewayerviceMockCreateResults{i1, err}
	return e.mock
}

// Create implements service.NoteService
func (mmCreate *gatewayerviceMock) Create(ctx context.Context, info *model.NoteInfo) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, info)
	}

	mm_params := gatewayerviceMockCreateParams{ctx, info}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_got := gatewayerviceMockCreateParams{ctx, info}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("gatewayerviceMock.Create got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the gatewayerviceMock.Create")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, info)
	}
	mmCreate.t.Fatalf("Unexpected call to gatewayerviceMock.Create. %v %v", ctx, info)
	return
}

// CreateAfterCounter returns a count of finished gatewayerviceMock.Create invocations
func (mmCreate *gatewayerviceMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of gatewayerviceMock.Create invocations
func (mmCreate *gatewayerviceMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to gatewayerviceMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mgatewayerviceMockCreate) Calls() []*gatewayerviceMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*gatewayerviceMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *gatewayerviceMock) MinimockCreateDone() bool {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateInspect logs each unmet expectation
func (m *gatewayerviceMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to gatewayerviceMock.Create with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to gatewayerviceMock.Create")
		} else {
			m.t.Errorf("Expected call to gatewayerviceMock.Create with params: %#v", *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		m.t.Error("Expected call to gatewayerviceMock.Create")
	}
}

type mgatewayerviceMockGet struct {
	mock               *gatewayerviceMock
	defaultExpectation *gatewayerviceMockGetExpectation
	expectations       []*gatewayerviceMockGetExpectation

	callArgs []*gatewayerviceMockGetParams
	mutex    sync.RWMutex
}

// gatewayerviceMockGetExpectation specifies expectation struct of the gatewayervice.Get
type gatewayerviceMockGetExpectation struct {
	mock    *gatewayerviceMock
	params  *gatewayerviceMockGetParams
	results *gatewayerviceMockGetResults
	Counter uint64
}

// gatewayerviceMockGetParams contains parameters of the gatewayervice.Get
type gatewayerviceMockGetParams struct {
	ctx context.Context
	id  int64
}

// gatewayerviceMockGetResults contains results of the gatewayervice.Get
type gatewayerviceMockGetResults struct {
	np1 *model.Note
	err error
}

// Expect sets up expected params for gatewayervice.Get
func (mmGet *mgatewayerviceMockGet) Expect(ctx context.Context, id int64) *mgatewayerviceMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("gatewayerviceMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &gatewayerviceMockGetExpectation{}
	}

	mmGet.defaultExpectation.params = &gatewayerviceMockGetParams{ctx, id}
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the gatewayervice.Get
func (mmGet *mgatewayerviceMockGet) Inspect(f func(ctx context.Context, id int64)) *mgatewayerviceMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for gatewayerviceMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by gatewayervice.Get
func (mmGet *mgatewayerviceMockGet) Return(np1 *model.Note, err error) *gatewayerviceMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("gatewayerviceMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &gatewayerviceMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &gatewayerviceMockGetResults{np1, err}
	return mmGet.mock
}

// Set uses given function f to mock the gatewayervice.Get method
func (mmGet *mgatewayerviceMockGet) Set(f func(ctx context.Context, id int64) (np1 *model.Note, err error)) *gatewayerviceMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the gatewayervice.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the gatewayervice.Get method")
	}

	mmGet.mock.funcGet = f
	return mmGet.mock
}

// When sets expectation for the gatewayervice.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mgatewayerviceMockGet) When(ctx context.Context, id int64) *gatewayerviceMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("gatewayerviceMock.Get mock is already set by Set")
	}

	expectation := &gatewayerviceMockGetExpectation{
		mock:   mmGet.mock,
		params: &gatewayerviceMockGetParams{ctx, id},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up gatewayervice.Get return parameters for the expectation previously defined by the When method
func (e *gatewayerviceMockGetExpectation) Then(np1 *model.Note, err error) *gatewayerviceMock {
	e.results = &gatewayerviceMockGetResults{np1, err}
	return e.mock
}

// Get implements service.NoteService
func (mmGet *gatewayerviceMock) Get(ctx context.Context, id int64) (np1 *model.Note, err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, id)
	}

	mm_params := gatewayerviceMockGetParams{ctx, id}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.np1, e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_got := gatewayerviceMockGetParams{ctx, id}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("gatewayerviceMock.Get got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the gatewayerviceMock.Get")
		}
		return (*mm_results).np1, (*mm_results).err
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, id)
	}
	mmGet.t.Fatalf("Unexpected call to gatewayerviceMock.Get. %v %v", ctx, id)
	return
}

// GetAfterCounter returns a count of finished gatewayerviceMock.Get invocations
func (mmGet *gatewayerviceMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of gatewayerviceMock.Get invocations
func (mmGet *gatewayerviceMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to gatewayerviceMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mgatewayerviceMockGet) Calls() []*gatewayerviceMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*gatewayerviceMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *gatewayerviceMock) MinimockGetDone() bool {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetInspect logs each unmet expectation
func (m *gatewayerviceMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to gatewayerviceMock.Get with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to gatewayerviceMock.Get")
		} else {
			m.t.Errorf("Expected call to gatewayerviceMock.Get with params: %#v", *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		m.t.Error("Expected call to gatewayerviceMock.Get")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *gatewayerviceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *gatewayerviceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *gatewayerviceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetDone()
}
