version: "3"

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - "./grpc_server/local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  pg-prod:
    image: postgres:14-alpine3.17
    env_file:
      - "./grpc_server/prod.env"
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  migrator-local:
    build:
      context: .
      dockerfile: ./grpc_server/migration_local.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local

  migrator-prod:
    build:
      context: .
      dockerfile: ./grpc_server/migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-prod

  grpc-server:
    build:
      context: .
      dockerfile: ./grpc_server/grpc_server.Dockerfile
    ports:
      - "8080:8080"
  pg-admin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - "./grpc_server/local.env"
    ports:
      - "82:80"
  grpc-gateway:
    build:
      context: .
      dockerfile: ./grpc_gateway/Dockerfile
    ports:
      - "5000:5000"
